name: parsing-playground
version: 0.0.1.0
synopsis: Parsing things
description: Please see README.md
homepage: http://github.com/passy/parsing-playground#readme
license: BSD3
author: Pascal Hartig
maintainer: Pascal Hartig <phartig@rdrei.net>
category: Console
extra-source-files:
  - stack.yaml
  - README.md

ghc-options:
  - -Wall
  - -fwarn-tabs
  - -fwarn-incomplete-record-updates
  - -fwarn-monomorphism-restriction
  - -fwarn-unused-do-bind

dependencies:
  - base >= 4.7 && < 5
  - text
  - megaparsec

executables:
  playground:
    main: Main.hs
    source-dirs: src
    ghc-options:
      - -threaded
      - -rtsopts
      - -with-rtsopts=-N
      - -Wall
