name:                tree-serialize
version:             0.0.1

dependencies:
  - base >= 4.7 && < 5

executables:
  exe:
    source-dirs:      .
    main:             Main.hs

library:
  source-dirs: .
  exposed-modules:
    - Library

tests:
  spec:
    main: Spec.hs
    source-dirs: test
    ghc-options: -threaded -rtsopts -with-rtsopts=-N
    dependencies:
      - tree-serialize
      - hedgehog
